// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import * as path from "path";
import * as fs from "fs";
import { defineConfig, env } from "prisma/config";

const dotenv = require("dotenv");

const baseEnvPath = path.resolve(__dirname, ".env");
if (fs.existsSync(baseEnvPath)) {
  dotenv.config({ path: baseEnvPath });
}

if (process.env.ENV_FILE) {
  const runtimeEnvPath = path.resolve(process.env.ENV_FILE);
  if (fs.existsSync(runtimeEnvPath)) {
    // 런타임 env 는 base .env 위에 덮어쓴다.
    dotenv.config({ path: runtimeEnvPath, override: true });
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
