// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import * as path from "path";
import * as fs from "fs";
import { defineConfig } from "prisma/config";

// NODE_ENV에 따라 올바른 .env 파일 로드
const envPath = process.env.ENV_FILE
  ? path.resolve(process.env.ENV_FILE)
  : path.resolve(
      __dirname,
      process.env.NODE_ENV === "production" ? ".env.production" : ".env.local",
    );
if (fs.existsSync(envPath)) {
  // dotenv 수동 로드
  const dotenv = require("dotenv");
  dotenv.config({ path: envPath, override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] || "",
  },
});
